config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  resources :twits
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #root "devise/sessions#new"
  root "twits#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/twit.rb
class Twit < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :twits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /twits
  # GET /twits.json
  def index
    @twits = Twit.all.order("created_at DESC")
    @twit = Twit.new
  end

  # GET /twits/1
  # GET /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = current_user.twits.build
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits
  # POST /twits.json
  def create
    @twit = current_user.twits.build(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to twits_path, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to twits_path, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def twit_params
      params.require(:twit).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/twits_helper.rb
module TwitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twittle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <nav class="navbar is-info">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-5">Twittle</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if user_signed_in? %>
                <p class="control">
                  <% handle = "@" + current_user.username %>
                  <%= link_to handle, twits_path, class: "button is-info" %>
                </p>
                <p class="control">
                  <%= link_to "New Twit", twits_path, class: "button is-info is-inverted" %>
                </p>
                <p class="control">
                  <%= link_to "Edit Account Info", edit_user_registration_path, class: "button is-info" %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
                </p>
              <% else %>
                <p class="control">
                  <%= link_to "Sign In", new_user_session_path, class: "button is-info" %>
                </p>
                <p class="control">
                  <%= link_to "Sign Up", new_user_registration_path, class: "button is-info" %>
                </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/twits/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
    <article class="media box">
      <figure class="media-left">
        <p class="image is 64x64">
          <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
        </p>
      </figure>
      <div class="media-content">
        <%= render "twits/form" %>
      </div>
    </article>
  <% end %>
  
  <% @twits.each do |t| %>
    <div class="box">
      <article class="media">
        <div class="media-left">
          <figure class="image is 64x64">
            <%= gravatar_image_tag(t.user.email, size: 64, alt: t.user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <strong><%= t.user.name %></strong></ br>
            <small>@<%= t.user.username %></small></ br>
            <p><%= t.body %></p>
          </div>
          <% if user_signed_in? %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to t, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to edit_twit_path(t), class:"level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to t, method: :delete, data: { confirm: "Are you sure you want to delete this twit?" } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
              </div>
            </nav>
          <% end %>
        </div>
      </article>
    </div>
  <% end %>
</div>

app/views/twits/_form.html.erb
<%= simple_form_for(@twit) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :body, label: "Twit about it", input_html: { class: "textarea" },
      wrapper: false, label_html: { class: "label" }, placeholder: "Compose a new twit...",
      autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-info" %>
<% end %>

app/views/twits/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small><%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Twits</p>
						<p class="title is-6"><%= current_user.twits.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">1</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">100M</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/twits/_trends.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Trends</p>
    <a class="panel-block">Trend 1</a>
    <a class="panel-block">Trend 2</a>
    <a class="panel-block">Trend 3</a>
    <a class="panel-block">Trend 4</a>
    <a class="panel-block">Trend 5</a>
    <a class="panel-block">Trend 6</a>
  </nav>
</div>

app/views/twits/_who-to-follow.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading"> Who to Follow</p>
  
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small>@johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </nav>

</div>

app/views/twits/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Editing Twit </h1>
          <%= render "form", twit: @twit %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom"></nav>
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to "Cancel", twits_path, class: "button is-info" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/twits/index.html.erb
<section class="section">
  <div class="container">
    <div class="columns">
    	<% if user_signed_in? %>
    		<%= render 'profile' %>
    	<% else %>
       <%= render 'trends' %>
      <% end %>

       <%= render 'feed' %>
       <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/twits/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Create a New Twit </h1>
        <%= render "form", twit: @twit %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom"></nav>
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to "Cancel", twits_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/twits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @twit.body %>
</p>

<%= link_to 'Edit', edit_twit_path(@twit) %> |
<%= link_to 'Back', twits_path %>